### ISSUE TITLE
hubot bm whoami throwing error

### ISSUE THREAD

**Issue by SanjuTechie87** [Blazemeter/hubot-blazemeter#1]
I am trying the command Hubot bm whoami but it is throwing the error:

[Sun Jul 07 2019 11:52:16 GMT+0530 (India Standard Time)] ERROR ReferenceError: handleError is not defined
  at Request._callback (/Users/sudiptaroy/myhubot/node_modules/hubot-blazemeter/src/lib/handlers.coffee:62:12, <js>:86:9)
  at Request.self.callback (/Users/sudiptaroy/myhubot/node_modules/request/request.js:185:22)
  at Request.emit (events.js:198:13)
  at Request.<anonymous> (/Users/sudiptaroy/myhubot/node_modules/request/request.js:1161:10)
  at Request.emit (events.js:198:13)
  at IncomingMessage.<anonymous> (/Users/sudiptaroy/myhubot/node_modules/request/request.js:1083:12)
  at Object.onceWrapper (events.js:286:20)
  at IncomingMessage.emit (events.js:203:15)
  at endReadableNT (_stream_readable.js:1129:12)
  at process._tickCallback (internal/process/next_tick.js:63:19)

[Sun Jul 07 2019 11:52:16 GMT+0530 (India Standard Time)] ERROR DOES NOT COMPUTE

Also I am not able to see anything for the below commands:

hubot bm list (tests|collections|masters|sessions)
hubot bm list running (tests|collections|masters|sessions)

Note : the environment and api key is already set

any help is much appreciated . thanks

**Comment by pgilad** [comment]
Hey we haven't maintained this for quite a while, but it looks like there are 2 issues:
1. `errorHandler` isn't defined correctly (it's defined as `exports.errorHandler`
2. The authorization to blazemeter has changed - it's now api-key-id and api-key-secret

**Comment by pgilad** [comment]
Thanks you for reporting this, fixed in https://github.com/Blazemeter/hubot-blazemeter/releases/tag/v2.0.0

**Comment by SanjuTechie87** [comment]
Hi Gilad, Thanks for acknowledging and updating the code. I am trying with the new updated source code, but I am not seeing the option to set bm set api key api id: secret key option when using the command Hubot help. 

myhubot bm get api key
myhubot bm get env
myhubot bm list (tests|collections|masters|sessions)
myhubot bm list running (tests|collections|masters|sessions)
myhubot bm run test <test_id>
myhubot bm set api key <apiKey>
myhubot bm set env <env>
myhubot bm stop test <test_id>
myhubot bm whoami

Note: I tried with providing my Blazemeter api key id: secret id but nothing is happening. Though the error has now changed. I am getting 401 unauthorised now .

Could you please look into it. Thanks in advance
